jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('jobs/department-states/', views.depttStateList, name="depttStateList"),

    path('jobs/tags', views.TagListView.as_view(), name="tagList"),
    path('jobs/tags/<slug:slug>', views.JobListByTagView.as_view(), name="job_list_by_tags"),
    path('jobs/list', views.JobListView.as_view(), name="jobList"),
    path('jobs/list_by_<str:keyword>', views.jobLists, name="list_by_type"),
    path('jobs/search', views.SearchListView.as_view(), name="search_results"),
    path('jobs/<slug:slug>', views.JobDetailView.as_view(), name="jobDetail"),
    path('archive/', views.archiveList, name="archiveList"),

    path('jobs/state/<slug:slug>', views.stateJobList, name='state_jobList'),
    path('jobs/department/<slug:slug>', views.depttJobList, name='deptt_jobList'),

    # path('jobs/create', views.JobCreateView.as_view(), name="createJob"),
    # path('jobs/<slug:slug>/update', views.JobUpdateView.as_view(), name="updateJob"),
    # path('jobs/<slug:slug>/delete', views.JobDeleteView.as_view(), name="deleteJob"),


]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about', views.AboutView.as_view(), name="about"),
    path('contact', views.contactView, name="contact"),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('disclaimer', views.DisclaimerView.as_view(), name="disclaimer"),
    path('tnc', views.TermNConditionView.as_view(), name="tnc"),
]

newsletters/urls.py
from django.urls import path
from . import views

app_name = 'newsletters'

urlpatterns = [
    path('new/', views.new, name="new"),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
]

website/urls.py
# from . import views

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# views for error handler
# from . import views
# sitemap
# from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.sitemaps.views import sitemap, index
from .sitemaps import StaticViewSitemap
from jobs.sitemaps import JobSitemap
from django.views.decorators.cache import cache_page


sitemaps = {
    'static': StaticViewSitemap,
    'jobs': JobSitemap,
}

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('not_for_you/secret_gate/panel_control/', admin.site.urls),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('accounts/', include('users.urls', namespace="users.urls")), # users url is imported as accounts path
    # path('tinymce/', include('tinymce.urls')),
    # path('users/', include('users.urls', namespace="users")),
    path('newsletters/', include('newsletters.urls', namespace="newsletters")),
    path('', include('main.urls', namespace="main")),
    path('', include('jobs.urls', namespace="jobs")),
    path('sitemap.xml', cache_page(86400)(index), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('taggit_autosuggest', include('taggit_autosuggest.urls')),
    path('maintenance-mode/', include("maintenance_mode.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]


# handler404 = "views.page_not_found_view"
# # handler500 = "views.server_error_view"
# handler403 = "views.permission_denied_view"
# # handler400 = "views.bad_request_view"

templates/partials/_footer.html
{% load static %}
<!-- Footers -->
  <footer class="footer_area section_padding_130_0 bg-white">

    <div class="container align-items-center justify-content-center text-center p-0">
      <form method="post" action="{% url 'newsletters:new' %}" class="row justify-content-center align-items-center g-3">
        {% csrf_token %}
        <div class="col-7 col-sm-6 mx-0 my-0 p-0">
          <input type="email" name="email" class="form-control form-control-lg rounded-pill bg-light" placeholder="Enter email here..." />
        </div>
        <div class="col-auto mx-3 my-0 p-0">
          <button type="submit" class="btn btn-lg btn-primary mb-3 rounded-pill">Subscribe</button>
        </div>
      </form>
    </div>

    <div class="container">
      <div class="row">
        <!-- Single Widget-->
        <div class="col-12 col-sm-6 col-lg-4 my-3">
          <div class="single-footer-widget">
            <!-- Footer Logo-->
            <div class="footer-logo">
              <img src="{% static 'img/logo.webp' %}" alt="SarkariVigyaapan" style="height: 60px; width: 60px; margin-top: -10px;" class="d-inline-block align-text-top">
            </div>
            <!-- <p>Appland is completely creative, lightweight, clean app landing page.</p> -->

            <!-- Copywrite Text-->
            <div class="copywrite-text mb-4">
              <p class="mb-0">Made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="#">us.</a></p>
            </div>
            <!-- Footer Social Area-->
            <div class="footer_social_area">
              <a href="https://www.facebook.com/sarkarivig" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                <i class="fa fa-facebook"></i>
              </a>
              <a href="https://www.youtube.com/@sarkarivigyaapan" data-toggle="tooltip" data-placement="top" title="" data-original-title="Youtube">
                <i class="fa fa-youtube"></i>
              </a>
              <a href="https://www.instagram.com/vigsarkari/" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                <i class="fa fa-instagram"></i>
              </a>
              <a href="https://t.me/vigsarkari" data-toggle="tooltip" data-placement="top" title="" data-original-title="Telegram">
                <i class="fa fa-telegram"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Single Widget-->
        <div class="col-12 col-sm-6 col-lg my-3">
          <div class="single-footer-widget">
            <!-- Widget Title-->
            <h5 class="widget-title">About</h5>
            <!-- Footer Menu-->
            <div class="footer_menu">
              <ul>
                <li><a href="{% url 'main:about' %}">About Us</a></li>
                <li><a href="{% url 'main:privacy-policy' %}">Privacy Policy</a></li>
                <li><a href="{% url 'main:disclaimer' %}">Disclaimer</a></li>
                <li><a href="{% url 'main:tnc' %}">Terms &amp; Conditions</a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Single Widget-->
        <div class="col-12 col-sm-6 col-lg my-3">
          <div class="single-footer-widget">
            <!-- Widget Title-->
            <h5 class="widget-title">Contact</h5>
            <!-- Footer Menu-->
            <div class="footer_menu">
              <ul>
                <li><a href="{% url 'main:contact' %}">Email Us</a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Single Widget-->
        <div class="col-12 col-sm-6 col-lg my-3">
          <div class="single-footer-widget">
            <!-- Widget Title-->
            <h5 class="widget-title">Miscellaneous</h5>
            <!-- Footer Menu-->
            <div class="footer_menu">
              <ul>
                <li><a href="/sitemap.xml">Sitemap</a></li>
                <li><a href="{% url 'jobs:search_results' %}">Find jobs</a></li>
                <li><a href="{% url 'jobs:tagList' %}">Tags</a></li>
                <li><a href="{% url 'jobs:archiveList' %}">Archive</a></li>
                <!-- <li><a href="#">Help &amp; Support</a></li> -->
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
<!-- End of .container -->

templates/partials/_header.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light p-0 bg-white navbar-shadow">
  <div class="container">
    <a class="navbar-brand" href="{% url 'main:index' %}">
      <img src="{% static 'img/logo.webp' %}" alt="SarkariVigyaapan" style="height: 60px; width: 60px;" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'main:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs:search_results' %}">Find Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs:list_by_type' 'result' %}">Result</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs:list_by_type' 'admit-card' %}">Admit Card</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs:list_by_type' 'answer-key' %}">Answer Key</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jobs:depttStateList' %}">Department</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:contact' %}">Contact us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <!-- Navbar -->

templates/partials/_pagination.html
<!-- Pagination -->

<div class="container my-3">
    <div class="row">
        <ul class="pagination justify-content-center">
            
              <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                
                  <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}" class="page-link mx-1">Previous</a>
                
              </li>
            
              
              {% for page in paginator.page_range %}
                <li class="page-item "><a class="page-link {% if page == page_obj.number %}active{% endif %} mx-1" href="?page={{ page }}">{{page}}</a></li>
              {% endfor %}

            
            
              <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}" class="page-link mx-1">Next</a>
              </li>
            
          </ul>
    </div>
</div>

templates/partials/_search_hero.html
<div
class="container align-items-center justify-content-center text-center p-5 pb-3"
>
<div class="row">
  <h3 id="sub-heading">Looking to get your dream</h3>
  <h1 id="heading">Sarkari Job</h1>
</div>
<div class="row my-2"></div>
<form method="GET" action="{% url 'jobs:search_results' %}" class="row justify-content-center align-items-center g-3">
  <div class="col-10 col-sm-6 mx-0 my-0">
    <input
      type="text"
      class="form-control form-control-lg rounded-pill bg-light"
      placeholder="Search job, category, department or state here..."
      name="search"
    />

  </div>
  <div class="col-auto mx-0 my-0">
    <button type="submit" class="btn btn-lg btn-primary mb-3 rounded-pill">
      Search
    </button>
  </div>
</form>
</div>

templates/partials/_share.html
{% load social_share %}

    <!-- Share page -->
    <!-- <div class="container my-3">
        <div class="row justify-content-center">
          <div class="col-6 d-flex justify-content-center gap-4">
            {% post_to_facebook object_or_url '<i class="fa fa-facebook"></i>' %}
            {% post_to_twitter "SarkariVigyapan: {{object.title}}. Check it out!" object_or_url '<i class="fa fa-twitter"></i>' %}
            {% post_to_telegram "SarkariVigyapan: {{object.title}}" object_or_url '<i class="fa fa-telegram"></i>' %}
          </div>
        </div>
      </div> -->
      <!-- Share page -->


      <!-- Fixed share section -->
      <div class="d-inline-block bg-white start-0 position-fixed top-50 px-2 py-3 fixed_social">
        {% post_to_facebook object_or_url '<i class="fa fa-facebook my-2 fs-5"></i>' %}
        {% post_to_twitter "SarkariVigyapan: {{object.title}}. Check it out!" object_or_url '<i class="fa fa-twitter my-2 fs-5"></i>' %}
        {% post_to_telegram "SarkariVigyapan: {{object.title}}" object_or_url '<i class="fa fa-telegram my-2 fs-5"></i>' %}
        {% post_to_whatsapp object_or_url '<i class="fa fa-whatsapp my-2 fs-5"></i>' %}
      </div>
      <!-- Fixed share section ends here -->