jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('jobs/department-states/', views.depttStateList, name="depttStateList"),

    path('jobs/tags', views.TagListView.as_view(), name="tagList"),
    path('jobs/tags/<slug:slug>', views.JobListByTagView.as_view(), name="job_list_by_tags"),
    path('jobs/list', views.JobListView.as_view(), name="jobList"),
    path('jobs/list_by_<str:keyword>', views.jobLists, name="list_by_type"),
    path('jobs/search', views.SearchListView.as_view(), name="search_results"),
    path('jobs/<slug:slug>', views.JobDetailView.as_view(), name="jobDetail"),
    path('archive/', views.archiveList, name="archiveList"),

    path('jobs/state/<slug:slug>', views.stateJobList, name='state_jobList'),
    path('jobs/department/<slug:slug>', views.depttJobList, name='deptt_jobList'),

    # path('jobs/create', views.JobCreateView.as_view(), name="createJob"),
    # path('jobs/<slug:slug>/update', views.JobUpdateView.as_view(), name="updateJob"),
    # path('jobs/<slug:slug>/delete', views.JobDeleteView.as_view(), name="deleteJob"),


]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about', views.AboutView.as_view(), name="about"),
    path('contact', views.contactView, name="contact"),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('disclaimer', views.DisclaimerView.as_view(), name="disclaimer"),
    path('tnc', views.TermNConditionView.as_view(), name="tnc"),
]

website/urls.py
# from . import views

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# views for error handler
# from . import views
# sitemap
# from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.sitemaps.views import sitemap, index
from .sitemaps import StaticViewSitemap
from jobs.sitemaps import JobSitemap
from django.views.decorators.cache import cache_page


sitemaps = {
    'static': StaticViewSitemap,
    'jobs': JobSitemap,
}

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('not_for_you/secret_gate/panel_control/', admin.site.urls),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('accounts/', include('users.urls', namespace="users.urls")), # users url is imported as accounts path
    # path('tinymce/', include('tinymce.urls')),
    # path('users/', include('users.urls', namespace="users")),
    path('newsletters/', include('newsletters.urls', namespace="newsletters")),
    path('', include('main.urls', namespace="main")),
    path('', include('jobs.urls', namespace="jobs")),
    path('sitemap.xml', cache_page(86400)(index), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('taggit_autosuggest', include('taggit_autosuggest.urls')),
    path('maintenance-mode/', include("maintenance_mode.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]


# handler404 = "views.page_not_found_view"
# # handler500 = "views.server_error_view"
# handler403 = "views.permission_denied_view"
# # handler400 = "views.bad_request_view"

main/models.py
from django.db import models

# Create your models here.
# class Main(models.Model):
#     page = models.CharField(max_length=100)
#     about = models.TextField(max_length=300)

#     def __str__(self):
#         return self.page

main/forms.py
from django import forms
from django.conf import settings

class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=150)
    subject = forms.CharField(max_length=100, help_text="Mention whether it's a Query or Report")
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

    # def is_valid(self, form):
    #     body = {
    #         'your_name': form.cleaned_data['your_name'],
    #         'email': form.cleaned_data['email'],
    #         'subject': form.cleaned_data['subject'],
    #         'message': form.cleaned_data['message'],
    #     }
    #     email_body = f'Hi Admin/Team \n\n {body[message]} \n\n {body[your_name]}'
    #     try:
    #         send_email(body['subject'], email_body, body['email'], settings.FROM_EMAIL)
    #     except BadHeaderError:
    #         messages.error('Invalid header')
        
    #     return redirect('main:contact')

main/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
# from django.views.generic.edit import FormView
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt


# from .models import Main
from jobs.models import Job
from .forms import ContactForm
from django.conf import settings

from taggit.models import Tag



# Create your views here.

class IndexView(TemplateView):
    template_name = "main/index.html"
    # extra_context = {'jobs': Job.objects.filter(is_published=True).values('post_title')}
    # extra_context = {'site' : Main.objects.get(page__icontains="home")}

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['job_notifications'] = Job.objects.filter(is_published=True).order_by('-created_on').values('post_title', 'slug')[:10]
        context['job_by_results'] = Job.objects.filter( result_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')[:10]
        context['featured_jobs'] = Job.objects.filter(is_featured=True, is_published=True).order_by('-created_on').values('post_title', 'slug', 'total_posts', 'application_expiry_date')[:6]
        context['job_by_admitcards'] = Job.objects.filter(admit_card_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')[:10]
        context['job_by_answerkey'] = Job.objects.filter(answerkey_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')[:10]
        context['job_syllabus'] = Job.objects.filter(syllabus_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')[:10]
        context['admissions'] = Job.objects.filter( is_admission=True, is_published=True).order_by('-updated_on').values('post_title', 'slug')[:10]
        context['categories'] = Tag.objects.all().distinct()[:50]

        return context


class AboutView(TemplateView):
    template_name = "main/about.html"

# class ContactView(FormView):
#     template_name = "main/contact.html"
#     form_class = ContactForm
#     # extra_context = {'site' : Main.objects.get(page__icontains="contact")}

#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         if form.is_valid():
#             body = {
#                 'your_name': form.cleaned_data['your_name'],
#                 'email': form.cleaned_data['email'],
#                 'subject': form.cleaned_data['subject'],
#                 'message': form.cleaned_data['message'],
#             }
#             email_body = f'Hi Admin/Team \n\n {body['message']} \n\n {body['your_name']}'
#             try:
#                 send_email(body['subject'], email_body, body['email'], settings.FROM_EMAIL)
#             except BadHeaderError:
#                 messages.error('Invalid header')
#             # return self.form_valid(form)
#             return redirect('main:contact')
#         else:
#             return self.form_invalid(form)


@csrf_exempt
def contactView(request):
    form = None
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            your_name = form.cleaned_data['your_name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email_body = f'Hi Admin/Team \n\n {message} \n\n {your_name}'

            try:
                send_mail(subject, email_body, email, (settings.FROM_EMAIL,))
                messages.success(request, "Your email has been sent...")
            except BadHeaderError:
                messages.error('Invalid header...')

            return redirect('main:contact')

    form = ContactForm()
    return render(request, 'main/contact.html', {'form': form})


class PrivacyPolicyView(TemplateView):
    template_name = 'main/privacy-policy.html'


class DisclaimerView(TemplateView):
    template_name = 'main/disclaimer.html'


class TermNConditionView(TemplateView):
    template_name = 'main/tnc.html'

templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block pagetitle %}
  | About
{% endblock pagetitle %}

{% block meta %}
  <meta name="description" content="SarkariVigyaapan- A government job notifications portal. Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result">
{% endblock meta %}


{% block meta_opengraph %}
  <!-- for opengraph -->
  <meta property="og:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta property="og:url" content={{request.build_absolute_uri}}>
  <meta property="og:description" content="SarkariVigyaapan- A government job notifications portal">
  <!--  -->
{% endblock meta_opengraph %}


{% block meta_twitter %}
  <!-- for twitter-card -->
  <meta name="twitter:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:description" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:url" content="{{request.build_absolute_uri}}">
  <!-- ..... -->
{% endblock meta_twitter %}

{% block content %}
  <div class="container my-5 p-5">
    <div class="row">
      <div class="container">
        <h1 class="text-center"><strong>About Us!</strong></h1>
        <h3 class="text-center">
          Welcome To <span id="W_Name1">www.sarkarivigyaapan.com</span>
        </h3>
        <p>
          <span id="W_Name2">www.sarkarivigyaapan.com</span> is a Professional
          <span id="W_Type1">Job Listing</span> Platform. Here we will provide you
          only interesting content, which you will like very much. We're dedicated
          to providing you the best of <span id="W_Type2">Job Listing</span>, with a
          focus on dependability and
          <span id="W_Spec">Government Jobs notification</span>. We're working to
          turn our passion for <span id="W_Type3">Job Listing</span> into a booming
          online website. We hope you enjoy our <span id="W_Type4">Job Listing</span> as much as
          we enjoy offering them to you.
        </p>
        <p>
          I will keep posting more important posts on my Website for all of you.
          Please give your support and love.
        </p>
        <p style="font-weight: bold; text-align: center">
          Thanks For Visiting Our Site<br><br>
          <span style="
              color: blue;
              font-size: 16px;
              font-weight: bold;
              text-align: center;
            ">Have a nice day!</span>
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block extra_sheets %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock extra_sheets %}

{% block pagetitle %}
  | Contact us
{% endblock pagetitle %}

{% block meta %}
  <meta name="description" content="SarkariVigyaapan- A government job notifications portal. Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result">
{% endblock meta %}


{% block meta_opengraph %}
  <!-- for opengraph -->
  <meta property="og:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta property="og:url" content={{request.build_absolute_uri}}>
  <meta property="og:description" content="SarkariVigyaapan- A government job notifications portal">
  <!--  -->
{% endblock meta_opengraph %}


{% block meta_twitter %}
  <!-- for twitter-card -->
  <meta name="twitter:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:description" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:url" content="{{request.build_absolute_uri}}">
  <!-- ..... -->
{% endblock meta_twitter %}

{% block content %}

<div class="container-fluid m-0 my-5 px-0 py-5">
  <!-- <div class="row">
    <div class="col-12"> -->
      <h1 style="font-size: 48px; font-weight: 400;"><strong>Contact us</strong></h1>
    <!-- </div>
  </div> -->
    <div class="row d-flex align-items-center bg-white py-3">
        <div class="image col-12 col-sm-6 m-0 p-0">
            <img src="{% static 'img/contact.jpg' %}" alt="contact">
        </div>

        <div class="form-container col-12 col-sm-6 m-0 p-5">
            <form action="{% url 'main:contact'  %}" method="post">
              {% csrf_token %}
              {{ form.as_p}}

              <!-- <label for="fname">First Name</label>
              <input type="text" id="fname" name="firstname" placeholder="Your name..">

              <label for="lname">Last Name</label>
              <input type="text" id="lname" name="lastname" placeholder="Your last name..">

              <label for="email">Email</label>
              <input type="email" id="email" name="email" placeholder="Your email address..">

              <label for="subject">Subject</label>
              <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
           -->
              <input type="submit" value="Submit">
            </form>
          </div>
    </div>
    <!-- <div class="box">
        <div class="image">
            <img src="{% static 'img/contact.jpg' %}" alt="contact">
          </div>

        <div class="form-container">
            <form action="action_page.php">

              <label for="fname">First Name</label>
              <input type="text" id="fname" name="firstname" placeholder="Your name..">

              <label for="lname">Last Name</label>
              <input type="text" id="lname" name="lastname" placeholder="Your last name..">

              <label for="email">Email</label>
              <input type="email" id="email" name="email" placeholder="Your email address..">

              <label for="subject">Subject</label>
              <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

              <input type="submit" value="Submit">

            </form>
          </div>
    </div> -->
</div>


{% endblock content %}

templates/main/disclaimer.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
  <meta name="description" content="SarkariVigyaapan- A government job notifications portal. Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result">
{% endblock meta %}


{% block meta_opengraph %}
  <!-- for opengraph -->
  <meta property="og:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta property="og:url" content={{request.build_absolute_uri}}>
  <meta property="og:description" content="SarkariVigyaapan- A government job notifications portal">
  <meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
  <!--  -->
{% endblock meta_opengraph %}


{% block meta_twitter %}
  <!-- for twitter-card -->
  <meta name="twitter:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:description" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:url" content="{{request.build_absolute_uri}}">
  <meta name="twitter:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
  <!-- ..... -->
{% endblock meta_twitter %}

{% block pagetitle %}
  | Disclaimer
{% endblock pagetitle %}


{% block content %}

    <div class="container my-5">
        <div class="row">

        </div>
    </div>

{% endblock content %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}


{% block meta %}
  <meta name="description" content="SarkariVigyaapan- A government job notifications portal. Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result">
{% endblock meta %}

{% block meta_opengraph %}
  <!-- for opengraph -->
  <meta property="og:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta property="og:url" content={{request.build_absolute_uri}}>
  <meta property="og:description" content="Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
    <meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
  <!--  -->
{% endblock meta_opengraph %}

{% block meta_twitter %}
  <!-- for twitter-card -->
  <meta name="twitter:title" content="SarkariVigyaapan- A government job notifications portal">
  <meta name="twitter:description" content="Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="twitter:url" content="{{request.build_absolute_uri}}">
    <meta name="twitter:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
  <!-- ..... -->
{% endblock meta_twitter %}

{% block extra_sheets %}
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock extra_sheets %}

{% block pagetitle %}
    | Home
{% endblock pagetitle %}


{% block content %}
    <div class="container mt-5">
      <div class="row">
        <h1 id="welcome-text">Welcome to <span class="animate__animated animate__bounceIn d-inline-block">Sarkari Vigyaapan</span></h1>
      </div>
    </div>
    <!-- Hero section -->
    {% include 'partials/_search_hero.html' %}
    <!-- Hero section ends here -->

    <!-- Share page -->
    {% include 'partials/_share.html' %}
    <!-- Share page -->

    <!-- Category section -->
    <div class="container text-center">
      <div class="row">
        <h2 class="sectional-heading" style="padding: 10px;">Category</h2>
      </div>

      <!-- Tags -->
      <div class="container">
        <div class="row justify-content-center">
          <ul class="nav nav-pills container justify-content-center">

            {% for category in categories %}
              <li class="nav-item mx-1 my-1 category-pill bg-light fw-semibold">
                <a class="nav-link" aria-current="page" href="{% url 'jobs:job_list_by_tags' category.slug %}">{{category.name}}</a>
              </li>
            {% endfor %}

          </ul>
        </div>
      </div>
      <!-- Tags end here -->
    </div>
    <!-- Category section ends here -->

    <!-- Latest jobs section -->
    <div class="container pt-3 pb-3 mt-5">
        <div class="row text-center mb-3">
            <h2 class="sectional-heading">Latest jobs</h2>
            <p>Find the job that's perfect for you. latest new jobs everyday
            </p>
        </div>
        <div class="row justify-content-center">

            {% if featured_jobs %}

              {% for job in featured_jobs %}
                <div class="col-lg-3 col-sm-5 col-11 mb-3 rounded border bg-light py-3 px-4 m-3 card cards">
                    <div class="flex-grow-1">
                        <h4 style="font-weight: 700;">{{job.post_title}}</h4>
                    </div>
                    <div>
                        <p>Last date:
                          {% if job.application_expiry_date %}
                            {{ job.application_expiry_date|date:"M d, Y" }}
                          {% else %}
                            Not announced
                          {% endif %}
                        </p>
                    </div>
                    {% if job.total_posts %}
                      <div>
                        <strong><span style="color: #0d6efd;">{{ job.total_posts }} seats</span></strong>
                      </div>
                    {% endif %}
                  <!-- <p>Min-qualification: {{ job.minimun_qualification }}</p> -->
                  <a href="{% url 'jobs:jobDetail' job.slug %}" class="stretched-link" target="_blank"></a>
                </div>
              {% endfor %}

            {% endif %}

        </div>
    </div>
    <!-- Latest jobs section ends here-->

    <div class="container mb-3 p-0">
      <div class="row justify-content-center">
        <div class="col-auto justify-content-center">
          <a href="https://t.me/vigsarkari" target="_blank" class="text-center d-inline-block" style="text-decoration: none;">Follow us on telegram <i class="fa fa-telegram"></i></a>
        </div>
      </div>
    </div>

    <!-- Independent section -->
    <div class="container mb-5">
      <div class="row justify-content-evenly">
        <div class="col-md-4 my-3">
          <div class="card left-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Admit card</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">


              {% for job_notification in job_by_admitcards %}
                <a class="list-group-item bg-transparent" href="{% url 'jobs:jobDetail' job_notification.slug %}" target="_blank">{{ job_notification.post_title }}</a>
              {% endfor %}

              </ul>
            <a href="{% url 'jobs:list_by_type' 'admit-card' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
        <div class="col-md-4 my-3">
          <div class="card top-mid-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Result</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">


              {% for job_notification in job_by_results %}
                <a class="list-group-item bg-transparent" target="_blank" href="{% url 'jobs:jobDetail' job_notification.slug %}">{{ job_notification.post_title }}</a>
              {% endfor %}

            </ul>
            <a href="{% url 'jobs:list_by_type' 'result' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
        <div class="col-md-4 my-3 order-first order-sm-0">
          <div class="card right-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Vigyaapan</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">

              {% for job_notification in job_notifications %}
                <a class="list-group-item bg-transparent" target="_blank" href="{% url 'jobs:jobDetail' job_notification.slug %}">{{ job_notification.post_title }}</a>
              {% endfor %}

            </ul>
            <a href="{% url 'jobs:jobList' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
      <!-- </div>
    </div>
    <div class="container mb-5">
      <div class="row justify-content-evenly"> -->
        <div class="col-md-4 my-3">
          <div class="card right-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Answer key</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">

              {% for job_notification in job_by_answerkey %}
                <a class="list-group-item bg-transparent"  href="{% url 'jobs:jobDetail' job_notification.slug %}" target="_blank">{{ job_notification.post_title }}</a>
              {% endfor %}

            </ul>
            <a href="{% url 'jobs:list_by_type' 'answer-key' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
        <div class="col-md-4 my-3">
          <div class="card bottom-mid-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Syllabus</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">

              {% for job_notification in job_syllabus %}
                <a class="list-group-item bg-transparent" href="{% url 'jobs:jobDetail' job_notification.slug %}" target="_blank">{{ job_notification.post_title }}</a>
              {% endfor %}

            </ul>
            <a href="{% url 'jobs:list_by_type' 'syllabus' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
        <div class="col-md-4 my-3">
          <div class="card left-notification-card bg-light py-3 px-3">
            <div class="card-header bg-transparent">
              <h3 class="text-center m-0 notification-card-header">Admission</h3>
            </div>
            <ul class="list-group list-group-flush bg-transparent">

              {% for job_notification in admissions %}
                <a class="list-group-item bg-transparent" href="{% url 'jobs:jobDetail' job_notification.slug %}" target="_blank">{{ job_notification.post_title }}</a>
              {% endfor %}

            </ul>
            <a href="{% url 'jobs:list_by_type' 'admission' %}" class="text-center text-decoration-none">View more</a>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}