jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('jobs/department-states/', views.depttStateList, name="depttStateList"),

    path('jobs/tags', views.TagListView.as_view(), name="tagList"),
    path('jobs/tags/<slug:slug>', views.JobListByTagView.as_view(), name="job_list_by_tags"),
    path('jobs/list', views.JobListView.as_view(), name="jobList"),
    path('jobs/list_by_<str:keyword>', views.jobLists, name="list_by_type"),
    path('jobs/search', views.SearchListView.as_view(), name="search_results"),
    path('jobs/<slug:slug>', views.JobDetailView.as_view(), name="jobDetail"),
    path('archive/', views.archiveList, name="archiveList"),

    path('jobs/state/<slug:slug>', views.stateJobList, name='state_jobList'),
    path('jobs/department/<slug:slug>', views.depttJobList, name='deptt_jobList'),

    # path('jobs/create', views.JobCreateView.as_view(), name="createJob"),
    # path('jobs/<slug:slug>/update', views.JobUpdateView.as_view(), name="updateJob"),
    # path('jobs/<slug:slug>/delete', views.JobDeleteView.as_view(), name="deleteJob"),


]

website/urls.py
# from . import views

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# views for error handler
# from . import views
# sitemap
# from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.sitemaps.views import sitemap, index
from .sitemaps import StaticViewSitemap
from jobs.sitemaps import JobSitemap
from django.views.decorators.cache import cache_page


sitemaps = {
    'static': StaticViewSitemap,
    'jobs': JobSitemap,
}

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('not_for_you/secret_gate/panel_control/', admin.site.urls),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('accounts/', include('users.urls', namespace="users.urls")), # users url is imported as accounts path
    # path('tinymce/', include('tinymce.urls')),
    # path('users/', include('users.urls', namespace="users")),
    path('newsletters/', include('newsletters.urls', namespace="newsletters")),
    path('', include('main.urls', namespace="main")),
    path('', include('jobs.urls', namespace="jobs")),
    path('sitemap.xml', cache_page(86400)(index), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('taggit_autosuggest', include('taggit_autosuggest.urls')),
    path('maintenance-mode/', include("maintenance_mode.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]


# handler404 = "views.page_not_found_view"
# # handler500 = "views.server_error_view"
# handler403 = "views.permission_denied_view"
# # handler400 = "views.bad_request_view"

jobs/models.py
from django.db import models
from django.utils.text import slugify
# from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

# from django.conf import settings
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

# from taggit.managers import TaggableManager
from taggit_autosuggest.managers import TaggableManager

# for image uploading
from django.core.files import File
from io import BytesIO
from PIL import Image


# Create your models here.
class State(models.Model):
    # state_code = models.CharField(max_length=10, unique=True, null=False, blank=False)
    # state = models.CharField(max_length=30, null=True, blank=True)
    name = models.CharField(max_length=30, null=True, blank=True)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        return super(State, self).save(*args, **kwargs)
    # def get_default_state():
    #     return State.objects.all().first()

class Ministry(models.Model):
    name = models.CharField(max_length=180, null=True, blank=True)
    slug = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = 'Ministry'
        verbose_name_plural = 'Ministries'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        return super(Ministry, self).save(*args, **kwargs)


class Job(models.Model):
    # Education choices
    QUALIFICATION = [
        ('MATRIC', _('Matriculation')),
        ('INTERMEDIATE', _('Intermediate')),
        ('GRADUATION', _('Graduate/Bachelors')),
        ('POST-GRADUATION', _('Post-graduate/Masters')),
        ('DOCTORATE', _('Ph.D/Doctorate'))
    ]
    APPLICATION = [
        ('ONLINE', _('Online')),
        ('OFFLINE', _('Offline'))
    ]

    keywords = models.CharField(max_length=200, default="Default keywords", null=False, blank=False)

    advertisement_number = models.CharField(max_length=200, null=True, blank=True)
    post_title = models.CharField(max_length=200, default='Default name', null=False, blank=False)
    image = models.ImageField(upload_to='jobs_image/%Y/%m/', blank=True, null=True)
    state = models.ForeignKey(State, related_name="jobs", on_delete=models.SET_NULL, default=None, null=True, blank=True)
    ministry = models.ForeignKey(Ministry, related_name="jobs", on_delete=models.SET_NULL, default=None, null=True, blank=True)
    tags = TaggableManager()

    brief_intro = models.TextField(default='Brief introduction of the job post')
    content = HTMLField(null=True, blank=True)


    application_mode = models.CharField(max_length=30, choices=APPLICATION)
    application_link = models.URLField(null=True, blank=True, default='')

    age = HTMLField(default=15)
    minimum_qualification = models.CharField(max_length=50, choices=QUALIFICATION)

    total_posts = models.PositiveIntegerField(null=True, blank=True)
    application_fee = HTMLField(default="Not announced")


    notification_date = models.DateField(null=True, blank=True)
    application_expiry_date = models.DateField(null=True, blank=True)
    important_dates = HTMLField(default='''
    <p>Application Begin : <strong>Unannounced</strong></p>
    <p>Last Date for Apply Online : <strong>Unannounced</strong></p>
    <p>Pay Exam Fee Last Date : <strong>Unannounced</strong></p>
    <p>Admit Card Date : <strong>Unannounced</strong></p>
    <p>Exam Date : <strong>Unannounced</strong></p>
    ''')


    extra_info_box_1 = HTMLField(null=True, blank=True)
    extra_info_box_2 = HTMLField(null=True, blank=True)

    important_links = models.TextField(null=True, blank=True, default='')

    official_site = models.URLField(null=True, blank=True, default='')
    admit_card_link = models.URLField(null=True, blank=True, default='')
    notification_link = models.URLField(null=True, blank=True, default='')
    result_link = models.URLField(null=True, blank=True, default='')
    syllabus_link = models.URLField(null=True, blank=True, default='')
    answerkey_link = models.URLField(null=True, blank=True, default='')

    is_featured = models.BooleanField(default=False, verbose_name="Featured job?")
    is_admission = models.BooleanField(default=False, verbose_name="Is admission?")
    is_published = models.BooleanField(default=False, verbose_name="Published?")
    is_archived = models.BooleanField(default=False, verbose_name="Archived?")

    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    updated_on = models.DateTimeField(auto_now=True)

    slug = models.SlugField(max_length=300, blank=True, null=True, default='')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, default=None, null=True, blank=True)

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'
        get_latest_by = '-created_on'
        ordering=['-created_on']


    def __str__(self):
        return self.post_title


    def save(self, *args, **kwargs):
        if not self.slug and self.post_title:
            self.slug = slugify(self.post_title)
            # self.slug = slugify(self.post_title + "  " + str(self.state) + " " + str(self.total_posts))
        if self.image:
            picture = self.image
            if picture.size > 0.1*1024*1024:
                self.image = compress(picture)
        return super(Job, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('jobs:jobDetail', kwargs={"slug": self.slug})


def compress(image):
    im = Image.open(image)
    im_io = BytesIO()
    im.save(im_io, 'jpeg', quality=50, optimize=True)
    new_image = File(im_io, name=image.name)
    im.close()
    return new_image

jobs/views.py
# from django.http import HttpResponse
from django.shortcuts import render
# from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
#  CreateView, DeleteView
# from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
# from django.contrib.auth.mixins import (LoginRequiredMixin, UserPassesTestMixin)
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Job, State, Ministry
# from .forms import JobCreationUpdationForm

# from datetime import date

from taggit.models import Tag

# Create your views here.

def jobLists(request, keyword):
    print(keyword)
    job_list = None
    page_number = request.GET.get('page')

    # today = date.today()

    if keyword == 'admit-card':
        job_list = Job.objects.filter(admit_card_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')
    elif keyword == 'result':
        job_list = Job.objects.filter( result_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')
    elif keyword == 'syllabus':
        job_list = Job.objects.filter(syllabus_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')
    elif keyword == 'answer-key':
        job_list = Job.objects.filter(answerkey_link__isnull=False, is_published=True).order_by('-updated_on').values('post_title', 'slug')
    elif keyword == 'admission':
        job_list = Job.objects.filter(is_admission=True, is_published=True).order_by('-updated_on').values('post_title', 'slug')

    paginator = Paginator(job_list, 2) # Show 50 jobs per page.
    page_obj = paginator.get_page(page_number)

    return render(request, 'jobs/list_by_type.html', {'keyword': keyword, 'page_obj': page_obj, 'paginator': paginator})


class SearchListView(ListView):
    model = Job
    context_object_name = 'job_list'
    template_name = 'jobs/search_results.html'

    # queryset = Job.objects.filter(post_title__icontains="engineers")
    def get_queryset(self):
        query = self.request.GET.get('search', None)
        if query:
            return Job.objects.filter(
                Q(post_title__icontains=query) | Q(tags__name__icontains=query) | Q(ministry__name__icontains=query)
            ).distinct()


# class JobListView(LoginRequiredMixin, ListView):
class JobListView(ListView):
    model = Job
    template_name = "jobs/job_list.html"
    paginate_by = 50

class JobDetailView(DetailView):
    model = Job
    template_name = "jobs/job_detail.html"
    # pk_url_kwarg = 'pk'

class TagListView(ListView):
    template_name = 'jobs/tag_list.html'
    model = Tag

class JobListByTagView(ListView):
    model = Job
    template_name = "jobs/tag_detail_list.html"
    context_object_name = 'object_list'
    paginate_by = 50

    def get_queryset(self):
        return Job.objects.filter(tags__slug=self.kwargs.get('slug'))

def archiveList(request):
    return render(request, 'jobs/archive_page.html')


def depttStateList(request):
    states = State.objects.all()
    department = Ministry.objects.all()
    context = {
        'state_list': states,
        'department_list': department
    }

    return render(request, 'jobs/dept_and_state.html', context)

def depttJobList(request, slug):
    deptt = Ministry.objects.get(slug=slug)
    job_list = deptt.jobs.all()
    page_number = request.GET.get('page')
    paginator = Paginator(job_list, 50) # Show 50 jobs per page.
    page_obj = paginator.get_page(page_number)

    return render(request, 'jobs/list_by_type.html', {'keyword': deptt.name, 'page_obj': page_obj, 'paginator': paginator})

def stateJobList(request, slug):
    state = State.objects.get(slug=slug)
    job_list = state.jobs.all()
    page_number = request.GET.get('page')
    paginator = Paginator(job_list, 50) # Show 50 jobs per page.
    page_obj = paginator.get_page(page_number)

    return render(request, 'jobs/list_by_type.html', {'keyword': state.name, 'page_obj': page_obj, 'paginator': paginator})

# class JobCreateView(LoginRequiredMixin, CreateView):
#     model = Job
#     form_class = JobCreationUpdationForm
#     template_name = "jobs/add_update_job.html"

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)

# class JobUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Job
#     form_class = JobCreationUpdationForm
#     template_name = "jobs/add_update_job.html"

#     def test_func(self):
#         obj = self.get_object()
#         return obj.author == self.request.user

# class JobDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = Job
#     template_name = 'jobs/delete_job.html'
#     success_url = reverse_lazy('jobs:jobList')

#     def test_func(self):
#         obj = self.get_object()
#         return obj.author == self.request.user


# class SuperUserPassesTestMixin(LoginRequiredMixin, UserPassesTestMixin):
#     def test_func(self):
#         return self.request.user.is_superuser

#     def handle_no_permission(self):
#         return HttpResponse('<h1>Sorry, you are not authorised to access this page. Please, ask the admin...</h1>')

# class StateListView(SuperUserPassesTestMixin, ListView):
#     model = State
#     template_name = 'jobs/state_list.html'

# class StateCreateView(SuperUserPassesTestMixin, CreateView):
#     model = State
#     template_name = 'jobs/add_update_state.html'

# class StateUpdateView(SuperUserPassesTestMixin, UpdateView):
#     model = State
#     template_name = 'jobs/add_update_state.html'

# class StateDeleteView(SuperUserPassesTestMixin, DeleteView):
#     model = State
#     template_name = 'jobs/delete_state.html'

templates/jobs/dept_and_state.html
{% extends 'base.html' %}
{% load static %}


{% block pagetitle %}
    | Department and States
{% endblock pagetitle %}

{% block meta %}
  <meta name="description" content="SarkariVigyaapan- A government job notifications portal. Get all the government job notification and latest update on government vacancies. Sarkari Vigyaapan is committed to bring you every important job updates under single page. So what are you waiting for !!! Start yours at: www.sarkarivigyaapan.com">
  <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result">
  {% endblock meta %}

{% block meta_opengraph %}
<!-- for opengraph -->
<meta property="og:title" content="SarkariVigyaapan | Department and States">
<meta property="og:url" content={{request.build_absolute_uri}}>
<meta property="og:description" content="Lists of Department and States">
<meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
<!--  -->
{% endblock meta_opengraph %}

{% block meta_twitter %}
<!-- for twitter-card -->
<meta name="twitter:title" content="SarkariVigyaapan | Department and States">
<meta name="twitter:url" content="{{request.build_absolute_uri}}">
<meta name="twitter:description" content="Lists of Department and States">
<meta name="twitter:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
<!-- ..... -->
{% endblock meta_twitter %}


<!-- templates/books/search_results.html -->

{% block content %}
    <div class="container my-5 p-5 text-center">
        <div class="row">
            <h1><strong>Department and States</strong></h1>
        </div>
        <!--  -->
        <div class="row justify-content-center">

            <div class="col-10 col-sm-5 my-3 mx-2">
                <!--<div class="row">-->
                <!--    <h2>Department</h2>-->
                <!--</div>-->
                {% if department_list %}
                <div class="card bg-white py-3 px-3">

                  <ul class="list-group list-group-flush bg-transparent">

                          {% for department in department_list %}

                              <a class="list-group-item bg-transparent" href="{% url 'jobs:deptt_jobList' department.slug %}">{{ department.name }}</a>

                          {% endfor %}

                  </ul>
                </div>
                {% else %}
                Not available yet...
                {% endif %}

              </div>

            <div class="col-10 col-sm-5 my-3 mx-2">
                <!--<div class="row">-->
                <!--    <h2>States</h2>-->
                <!--</div>-->
                {% if state_list %}
                <div class="card bg-white py-3 px-3">

                    <ul class="list-group list-group-flush bg-transparent">

                            {% for state in state_list %}

                                <a class="list-group-item bg-transparent" href="{% url 'jobs:state_jobList' state.slug %}">{{ state.name }}</a>

                            {% endfor %}

                    </ul>
                </div>
                {% else %}
                Not available yet...
                {% endif %}

            </div>

        </div>

    </div>

{% endblock content %}

templates/jobs/job_detail.html
{% extends 'base.html' %}
{% load static %}


    {% block extra_sheets %}
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% endblock extra_sheets %}

    {% block meta %}
      <meta name="description" content="{{object.brief_intro}}">
      <meta name="keywords" content="{{object.keywords}}">
    {% endblock meta %}

    {% block meta_opengraph %}
      <!-- for opengraph -->
      <meta property="og:title" content="{{ object.post_title }}">
      <meta property="og:url" content={{request.build_absolute_uri}}>
      <meta property="og:description" content="{{object.brief_intro|slice:':88'}}">
      {% if object.image %}
          <meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{{object.image.url}}">
      {% endif %}
      <!--  -->
    {% endblock meta_opengraph %}

    {% block meta_twitter %}
      <!-- for twitter-card -->
      <meta name="twitter:title" content="{{ object.post_title }}">
      <meta name="twitter:url" content="{{request.build_absolute_uri}}">
      <meta name="twitter:description" content="{{object.brief_intro|slice:':88'}}">
        {% if object.image %}
          <meta name="twitter:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{{object.image.url}}">
        {% endif %}
      <!-- ..... -->
    {% endblock meta_twitter %}


    {% block pagetitle %}
      {{ object.post_title }}
    {% endblock pagetitle %}


    {% block content %}
      <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light">
            <hr>
            <!-- <h1>Bihar BPSC 68th Recruitment 2022 Apply Online for 281 Post</h1> -->
            <h1>{{ object.post_title }} {{ object.application_mode }}
                {% if object.total_posts %}
                  for {{ object.total_posts }} posts
                {% endif %}
            </h1>
            <hr>
            <br>
            {% if object.image %}
              <div class="container-fluid mb-3">
                <div class="row justify-content-center">
                  <img src="{{object.image.url}}" alt="{{object.post_title}}" style="object-fit:cover; max-height: 500px; padding: 0;">
                </div>
              </div>
            {% endif %}

            {% if object.notification_date %}
              <h2>{{ object.notification_date }}</h2>
            {% endif %}

            <br>
            <p>
              {{ object.brief_intro}}
            </p>
            <ul>
              <li>Minimum qualification: <strong>{{object.minimum_qualification}}</strong> </li>
            </ul>

            <div class="container my-3">
              <div class="row">
                <ul class="nav nav-pills container justify-content-center">

                  {% for tag in object.tags.all %}
                    <li class="nav-item mx-1 my-1 category-pill bg-light fw-semibold">
                      <a class="nav-link" aria-current="page" href="{% url 'jobs:job_list_by_tags' tag.slug %}">{{tag.name}}</a>
                    </li>
                  {% endfor %}

                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <!--  -->
      <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light">
            <hr>
            <h1>{{object.post_title}} vacancy details</h1>
            <hr>
            <br>
            <div class="container-fluid overflow-scroll">
              {% if object.content %}
                {{object.content|safe}}
              {% else %}
                <h2>Will be updated soon...</a></h2>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!--  -->
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-10 col-sm-4 detail-card p-4 mb-5 mx-1 justify-content-center bg-light">
            <hr>
            <h1>Important Dates</h1>
            <hr>
            <br>
            <div class="container-fluid overflow-scroll">
                {{ object.important_dates|safe}}
            </div>
            <!--<ul>-->
            <!--  <li>Application Begin :-->
            <!--  {% if object.online_application_date %}-->
            <!--  <strong>{{object.online_application_date}}</strong>-->
            <!--  {% else %}-->
            <!--    To be announced-->
            <!--  {% endif %}-->
            <!--    </li>-->
            <!--  <li>Last Date for Apply Online :-->
            <!--  {% if object.application_expiry_date %}-->
            <!--  <strong>{{object.application_expiry_date|date:"M d, Y"}}</strong>-->
            <!--  {% else %}-->
            <!--    To be announced-->
            <!--  {% endif %}-->
            <!--  </li>-->
            <!--  <li>Pay Exam Fee Last Date :-->
            <!--    {% if object.fee_last_date %}-->
            <!--    <strong>{{object.fee_last_date}}</strong>-->
            <!--    {% else %}-->
            <!--      Unannounced-->
            <!--    {% endif %}-->
            <!--  </li>-->

            <!--  <li>Admit Card Date :-->
            <!--    {% if object.admit_card_date %}-->
            <!--      <strong>{{object.admit_card_date}}</strong>-->
            <!--    {% else %}-->
            <!--      Unannounced-->
            <!--    {% endif %}-->
            <!--  </li>-->

            <!--  {% if object.correction_date %}-->
            <!--  <li>Correction Last Date : <strong>{{object.correction_date}}</strong></li>-->
            <!--  {% endif %}-->

            <!--  <li>Exam Date :-->
            <!--    {% if object.exam_date %}-->
            <!--      <strong>{{object.exam_date}}</strong>-->
            <!--    {% else %}-->
            <!--      Unannounced-->
            <!--    {% endif %}-->
            <!--  </li>-->
            <!--</ul>-->
          </div>
          <div class="col-10 col-sm-4 detail-card p-4 mb-5 mx-1 justify-content-center bg-light">
            <hr>
            <h1>Application Fee</h1>
            <hr>
            <br>
            <div class="container-fluid overflow-scroll">
                {% if object.application_fee %}
                    {{object.application_fee|safe}}
                {% else %}-->
                      Unannounced
                {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!---->
      {% if object.extra_info_box_1 %}
          <div class="container mb-5">
            <div class="row justify-content-center">
              <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light overflow-scroll">
                <hr>
                <br>
                {{object.extra_info_box_1|safe}}

              </div>
            </div>
          </div>
      {% endif %}

      <!---->

        <!---->
          {% if object.extra_info_box_2 %}
              <div class="container mb-5">
                <div class="row justify-content-center">
                  <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light overflow-scroll">
                    <hr>
                    <br>
                    {{object.extra_info_box_2|safe}}

                  </div>
                </div>
              </div>
          {% endif %}

          <!---->
      <!--  -->
      <div class="container mb-5">
        <div class="row justify-content-center">
          <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light">
            <hr>
            <h1>Age Limit</h1>
            <hr>
            <br>
            <div class="container-fluid overflow-scroll">
                {{object.age|safe}}
            </div>
          </div>
        </div>
      </div>
      <!--  -->
      <div class="container mb-5">
        <div class="row justify-content-center">
          <div class="col-10 col-sm-8 detail-card p-4 justify-content-center bg-light">
            <hr>
            <h1>Some Useful Important Links</h1>
            <hr>
            <br>
            <div class="grid-container">
              {% if object.notification_link %}
                <a href="{{object.notification_link}}" class="text-decoration-none"><div class="grid-item">Download notification</div></a>
              {% else %}
                <div class="grid-item">Notification link will be updated soon...</div>
              {% endif %}

              {% if object.application_link %}
                <a href="{{object.application_link}}" class="text-decoration-none"><div class="grid-item">Apply online</div></a>
              {% else %}
                <div class="grid-item">Application link will be updated soon...</div>
              {% endif %}

              {% if object.syllabus_link %}
                <a href="{{object.syllabus_link}}" class="text-decoration-none"><div class="grid-item">Syllabus</div></a>
              {% else %}
                <div class="grid-item">Syllabus link will be updated soon...</div>
              {% endif %}

              {% if object.admit_card_link %}
                <a href="{{object.admit_card_link}}" class="text-decoration-none"><div class="grid-item">Admit card</div></a>
              {% else %}
                <div class="grid-item">Admit card link will be updated soon...</div>
              {% endif %}

              {% if object.result_link %}
                <a href="{{object.result_link}}" class="text-decoration-none"><div class="grid-item">Download result</div></a>
              {% else %}
                <div class="grid-item">Result link will be updated soon...</div>
              {% endif %}

              {% if object.official_site %}
                <a href="{{object.official_site}}" class="text-decoration-none"><div class="grid-item">Official website</div></a>
              {% else %}
                <div class="grid-item">Official website link will be updated soon...</div>
              {% endif %}

              <a href="https://t.me/vigsarkari" class="text-decoration-none"><div class="grid-item">Join us on Telegram</div></a>
            </div>
          </div>
        </div>
      </div>
      <!--  -->

      <!-- Share page -->
      {% include 'partials/_share.html' %}
      <!-- Share page -->

    {% endblock content %}

templates/jobs/tag_list.html
{% extends 'base.html' %}
{% load static %}

{% block pagetitle %}
    | Tags list
{% endblock pagetitle %}

{% block meta %}
      <meta name="description" content="SarkariVigyaapan- A government job notifications portal">
      <meta name="keywords" content="सरकारी विज्ञापन, sarkari exam, sarkari network, sarkari job, sarkari naukri, sarkari result"
{% endblock meta %}

{% block meta_opengraph %}
<!-- for opengraph -->
<meta property="og:title" content="SarkariVigyaapan | Tags list">
<meta property="og:url" content={{request.build_absolute_uri}}>
<meta property="og:description" content="Lists of tags">
<meta property="og:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
<!--  -->
{% endblock meta_opengraph %}

{% block meta_twitter %}
<!-- for twitter-card -->
<meta name="twitter:title" content="SarkariVigyaapan | Tags list">
<meta name="twitter:url" content="{{request.build_absolute_uri}}">
<meta name="twitter:description" content="Lists of tags">
<meta name="twitter:image" content="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'img/logo.webp' %}">
<!-- ..... -->
{% endblock meta_twitter %}

{% block content %}
        <!-- Category section -->
          <div class="container text-center my-5 p-5">
            <div class="row">
              <h1 class="sectional-heading" style="padding: 10px;">Tags</h1>
            </div>

            <!-- Tags -->
            <div class="container">
              <div class="row justify-content-center">
                <ul class="nav nav-pills container justify-content-center">

                  {% for tag in tag_list %}
                    <li class="nav-item mx-1 my-1 category-pill bg-light fw-semibold">
                      <a class="nav-link" aria-current="page" href="{% url 'jobs:job_list_by_tags' tag.slug%}" target="_blank">{{tag.name}}</a>
                    </li>
                  {% endfor %}

                </ul>
              </div>
            </div>
            <!-- Tags end here -->
          </div>
          <!-- Category section ends here -->
{% endblock content %}